// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data
const users = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'User',
    email: 'user@nextmail.com',
    password: '123456',
  },
];

const customers = [
  {
    id: 'd6e15727-9fe1-4961-8c5b-ea44a9bd81aa',
    name: 'Evil Rabbit',
    email: 'evil@rabbit.com',
    image_url: '/customers/evil-rabbit.png',
  },
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    name: 'Delba de Oliveira',
    email: 'delba@oliveira.com',
    image_url: '/customers/delba-de-oliveira.png',
  },
  {
    id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    name: 'Lee Robinson',
    email: 'lee@robinson.com',
    image_url: '/customers/lee-robinson.png',
  },
  {
    id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    name: 'Michael Novotny',
    email: 'michael@novotny.com',
    image_url: '/customers/michael-novotny.png',
  },
  {
    id: 'CC27C14A-0ACF-4F4A-A6C9-D45682C144B9',
    name: 'Amy Burns',
    email: 'amy@burns.com',
    image_url: '/customers/amy-burns.png',
  },
  {
    id: '13D07535-C59E-4157-A011-F8D2EF4E0CBB',
    name: 'Balazs Orban',
    email: 'balazs@orban.com',
    image_url: '/customers/balazs-orban.png',
  },
];

const invoices = [
  {
    customer_id: customers[0].id,
    amount: 15795,
    status: 'pending',
    date: '2022-12-06',
  },
  {
    customer_id: customers[1].id,
    amount: 20348,
    status: 'pending',
    date: '2022-11-14',
  },
  {
    customer_id: customers[4].id,
    amount: 3040,
    status: 'paid',
    date: '2022-10-29',
  },
  {
    customer_id: customers[3].id,
    amount: 44800,
    status: 'paid',
    date: '2023-09-10',
  },
  {
    customer_id: customers[5].id,
    amount: 34577,
    status: 'pending',
    date: '2023-08-05',
  },
  {
    customer_id: customers[2].id,
    amount: 54246,
    status: 'pending',
    date: '2023-07-16',
  },
  {
    customer_id: customers[0].id,
    amount: 666,
    status: 'pending',
    date: '2023-06-27',
  },
  {
    customer_id: customers[3].id,
    amount: 32545,
    status: 'paid',
    date: '2023-06-09',
  },
  {
    customer_id: customers[4].id,
    amount: 1250,
    status: 'paid',
    date: '2023-06-17',
  },
  {
    customer_id: customers[5].id,
    amount: 8546,
    status: 'paid',
    date: '2023-06-07',
  },
  {
    customer_id: customers[1].id,
    amount: 500,
    status: 'paid',
    date: '2023-08-19',
  },
  {
    customer_id: customers[5].id,
    amount: 8945,
    status: 'paid',
    date: '2023-06-03',
  },
  {
    customer_id: customers[2].id,
    amount: 1000,
    status: 'paid',
    date: '2022-06-05',
  },
];


// -----------------

const breeds = [
  {
    id: 'd6e15727-9fe1-4961-8c5b-ea44a9bd81aa',
    name: 'American Bulldog',
    email: 'evil@rabbit.com',
    image_url: '/customers/evil-rabbit.png',
  },
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    name: 'Airedale Terrier',
    email: 'delba@oliveira.com',
    image_url: '/customers/delba-de-oliveira.png',
  },
  {
    id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    name: 'Labrador Retriever',
    email: 'lee@robinson.com',
    image_url: '/customers/lee-robinson.png',
  },
  {
    id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    name: 'Chinook',
    email: 'michael@novotny.com',
    image_url: '/customers/michael-novotny.png',
  },
  {
    id: 'CC27C14A-0ACF-4F4A-A6C9-D45682C144B9',
    name: 'Chow Chow',
    email: 'amy@burns.com',
    image_url: '/customers/amy-burns.png',
  },
  {
    id: '13D07535-C59E-4157-A011-F8D2EF4E0CBB',
    name: 'Bolognese',
    email: 'balazs@orban.com',
    image_url: '/customers/balazs-orban.png',
  },
];

const traits = [
  {
    breed_id: breeds[0].id,
    affectionate_with_family: 0,
    good_with_other_dogs: 3,
    good_with_young_children: 3,
    shedding_level: 2,
    coat_grooming_frequency: 0,
    drooling_level: 0,
    openness_to_strangers: 0,
    playfulness_level: 0,
    watchdog_protective_nature: 0,
    adaptability_level: 0,
    trainability_level: 4,
    energy_level: 0,
    barking_level: 1,
    mental_stimulation_needs: 0,
  },
  {
    breed_id: breeds[1].id,
    affectionate_with_family: 3,
    good_with_other_dogs: 3,
    good_with_young_children: 3,
    shedding_level: 1,
    coat_grooming_frequency:3,
    drooling_level: 1,
    openness_to_strangers: 3,
    playfulness_level: 3,
    watchdog_protective_nature: 5,
    adaptability_level: 3,
    trainability_level: 3,
    energy_level: 3,
    barking_level: 3,
    mental_stimulation_needs: 3,
  },
  {
    breed_id: breeds[2].id,
    affectionate_with_family: 5,
    good_with_other_dogs: 5,
    good_with_young_children: 5,
    shedding_level: 4,
    coat_grooming_frequency: 2,
    drooling_level: 2,
    openness_to_strangers: 5,
    playfulness_level: 5,
    watchdog_protective_nature: 3,
    adaptability_level: 5,
    trainability_level: 5,
    energy_level: 5,
    barking_level: 3,
    mental_stimulation_needs: 4,
  },
  {
    breed_id: breeds[3].id,
    affectionate_with_family: 4,
    good_with_other_dogs: 5,
    good_with_young_children: 5,
    shedding_level: 3,
    coat_grooming_frequency: 3,
    drooling_level: 2,
    openness_to_strangers: 3,
    playfulness_level: 3,
    watchdog_protective_nature: 4,
    adaptability_level: 4,
    trainability_level: 4,
    energy_level: 3,
    barking_level: 5,
    mental_stimulation_needs: 3,
  },
  {
    breed_id: breeds[4].id,
    affectionate_with_family: 4,
    good_with_other_dogs: 3,
    good_with_young_children: 2,
    shedding_level: 3,
    coat_grooming_frequency: 3,
    drooling_level: 3,
    openness_to_strangers: 2,
    playfulness_level: 3,
    watchdog_protective_nature: 5,
    adaptability_level: 3,
    trainability_level: 3,
    energy_level: 3,
    barking_level: 1,
    mental_stimulation_needs: 3,
  },
  {
    breed_id: breeds[5].id,
    affectionate_with_family: 3,
    good_with_other_dogs: 3,
    good_with_young_children: 3,
    shedding_level: 1,
    coat_grooming_frequency: 3,
    drooling_level: 1,
    openness_to_strangers: 5,
    playfulness_level: 1,
    watchdog_protective_nature: 1,
    adaptability_level: 5,
    trainability_level: 5,
    energy_level: 1,
    barking_level: 1,
    mental_stimulation_needs: 1,
  },
];

const revenue = [
  { month: 'Jan', revenue: 2000 },
  { month: 'Feb', revenue: 1800 },
  { month: 'Mar', revenue: 2200 },
  { month: 'Apr', revenue: 2500 },
  { month: 'May', revenue: 2300 },
  { month: 'Jun', revenue: 3200 },
  { month: 'Jul', revenue: 3500 },
  { month: 'Aug', revenue: 3700 },
  { month: 'Sep', revenue: 2500 },
  { month: 'Oct', revenue: 2800 },
  { month: 'Nov', revenue: 3000 },
  { month: 'Dec', revenue: 4800 },
];


export { users, customers, invoices, revenue, breeds, traits };
